baseURL = "https://dzello.com/"
title = "Josh Dzielak - Developer tools and developer relations"
languageCode = "en-us"
copyright = "Copyright &copy; 2018 - Josh Dzielak"
canonifyurls = true
theme = "kiera"

paginate = 10
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Josh Dzielak"
    email = "jdzielak@gmail.com"
    twitter = "dzello"
    github = "dzello"
    linkedin = "dzello"
    instagram = "josh_people"
    facebook = ""

[params]
    description = "Personal site and blog with resources for people building developer tools"
    tagline = "Developer tools and developer relations"
    header = "Josh Dzielak - dzello.com"
    ogImage = "images/josh-dzielak-2018.png"
    ogImageWidth = "508"
    ogImageHeight = "506"
    githubURL = "https://github.com/dzello/dzello-dot-com"
    googleAnalytics = "UA-24132749-1"
