[build]
command = "npm run build"
publish = "dist"

[context.production.environment]
HUGO_VERSION = "0.36.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm run build-preview"

[context.deploy-preview.environment]
HUGO_VERSION = "0.36.1"

[context.branch-deploy]
command = "npm run build-preview"

[context.branch-deploy.environment]
HUGO_VERSION = "0.36.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
