---
upload_path: "/site/static/images"
frontmatter_file_url_template: "/site/static/images"
body_file_url_template: "/site/static/images"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
version: 0.38.1
