baseURL = "/"
title = "Josh Dzielak - Developer tools and developer relations"
languageCode = "en-us"
languageLang = "en"
paginate = 4
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[permalinks]
blog = "/blog/:year/:month/:day/:title/"
thailand = "/thailand/:year/:month/:day/:title/"

[blackfriday]
smartypants = false

[author]
name = "Josh Dzielak"
first_name = "Josh"
email = "josh@dzello.com"
twitter = "dzello"
github = "dzello"
linkedin = "dzello"
instagram = "josh_people"
calendly = "dzello"
computer = "🍎"
food = "🧀"
hometown = "Rockford, USA"
residence = "Paris, FR"
avatar = "josh-dzielak-profile-2018"

[params]
cl = "https://res.cloudinary.com/dzello/image/upload"
clv = "https://res.cloudinary.com/dzello/video/upload"
cl_grid_image_params = "f_auto,q_auto,w_400,h_300,c_fill,g_auto,bo_3px_solid_rgb:f26b38"
cl_grid_image_logo_params = "w_325/f_auto,q_auto,w_400,h_300,c_lpad,bo_3px_solid_rgb:f26b38"
copyright = "© Josh Dzielak 2018"
description = "Formerly of Algolia, Keen IO and Disney, Josh Dzielak shares his perspective on developer tools and developer relations."
header = "Josh Dzielak"
ogImage = "josh-dzielak-grand-palais-2018"
ogImageWidth = "1200"
ogImageHeight = "630"
ogImageClParams = "c_crop,g_face,f_auto,q_auto,w_1200,h_630"
githubURL = "https://github.com/dzello/dzello-dot-com"
googleAnalytics = "UA-24132749-1"
themeColor = "blue"
opensearch_short_name = "dzello.com"
opensearch_description = "Search for articles about developer relations on dzello.com"

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "content", "section", "path", "kind", "readingtime", "type", "weight", "url", "wordcount", "draft"]
params = ["image", "categories"]

[outputs]
home = ["HTML", "RSS", "Algolia", "OpenSearch"]
section = ["HTML", "RSS", "JSON"]
page = ["HTML", "JSON"]

[outputFormats.Algolia]
baseName = "algolia"
mediaType = "application/json"
isPlainText = true
notAlternative = true

[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true
