baseURL = "/"
title = "Josh Dzielak - Developer tools and developer relations"
languageCode = "en-us"
languageLang = "en"
copyright = "Copyright &copy; 2018 - Josh Dzielak"
paginate = 6
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[permalinks]
blog = "/:year/:month/:day/:title/"

[blackfriday]
smartypants = false

[author]
name = "Josh Dzielak"
email = "josh@dzello.com"
twitter = "dzello"
github = "dzello"
linkedin = "dzello"
instagram = "josh_people"
calendly = "dzello"

[params]
cl = "https://res.cloudinary.com/dzello/image/upload"
description = "Formerly of Algolia, Keen IO and Disney, Josh Dzielak shares his perspective on developer tools and developer relations."
copyright = "© 2018 Josh Dzielak. All rights reserved."
header = "Josh Dzielak"
ogImage = "josh-dzielak-frisbee-2015.png"
githubURL = "https://github.com/dzello/dzello-dot-com"
googleAnalytics = "UA-24132749-1"
themeColor = "blue"

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "content", "section", "path", "kind", "readingtime", "type", "weight", "url", "wordcount", "draft"]
params = ["image", "categories"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
section = ["HTML", "RSS", "JSON"]
page = ["HTML", "JSON"]

[outputFormats.Algolia]
baseName = "algolia"
mediaType = "application/json"
isPlainText = true
notAlternative = true
