backend:
  branch: master
  name: github
  repo: dzello/dzello-dot-com
media_folder: site/static/images
public_folder: site/images
collections:
  - name: blog
    label: Blog
    folder: site/content/blog
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Date, name: date, widget: datetime}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Categories, name: categories, widget: list}
  - name: work
    label: Work
    folder: site/content/work
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
  - name: thailand
    label: Thailand
    folder: site/content/thailand
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
      - {label: Date, name: date, widget: datetime}
      - {label: Draft, name: draft, widget: boolean, required: false}
      - {label: Categories, name: categories, widget: list}
  - name: data
    label: Data
    folder: site/data/work
    extension: toml
    format: toml-frontmatter
    create: true
    fields:
      - {label: text, name: body, widget: text}
  - name: pages
    label: Pages
    files:
      - file: site/content/_index.md
        label: Home Page
        name: home
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: Introduction, name: introduction, widget: string}
          - {label: Introduction Photo, name: introductionPhoto, widget: image}
      - file: site/content/about.md
        label: About
        name: about
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: site/content/consulting.md
        label: Consulting
        name: consulting
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: site/content/api.md
        label: API
        name: api
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
