backend:
  branch: master
  name: github
  repo: dzello/dzello-dot-com

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
